### PR TITLE
compileSkip setting analogous to testSkip

### PR DESCRIPTION
**Pull request by advayDev1**

### CODE REVIEW

**Comment by confile** [comment]
+1 I like the idea!

**Comment by advayDev1** [comment]
hopefully when we make this a real plugin starting tomorrow, we will use normal task.enabled = false.

this causes some issues, which I'm fixing (one sec...)

**Comment by brunobowden** [comment]
@advayDev1 - thanks for contributing, I only changed the description to make "compileSkip" the first word in the description.

**Comment by advayDev1** [comment]
@brunobowden  - sorry, commit race.  please merge in #82  as well

**Pull request merged**
